### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by turambar** [YerevaNN/mimic3-benchmarks#10]
Start filling out details of README to make it easier for folks to build the benchmarks, as well as contribute.

**Comment by omerdr** [comment]
Hi guys,

Thanks for releasing this project and the paper, this is really interesting work you guys are doing.
I'm trying to reproduce the results, and got stuck at step 5 of the README build instructions with the following error:
<pre><i>$ python scripts/extract_episodes_from_subjects.py data/root/ </i>
Subject 28943: reading...got 1 stays, 6 diagnoses, 3773 events...cleaning and converting to time series.../usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py:128: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/home/omer/code/3rdparty/mimic3-benchmarks/mimic3benchmark/preprocessing.py:157: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  v.ix[idx] = np.nan
/home/omer/code/3rdparty/mimic3-benchmarks/mimic3benchmark/preprocessing.py:149: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
<b>  v.ix[idx] = np.nan
Exception in clean_events: clean_height
number of rows: 0
values: Empty DataFrame
Columns: [SUBJECT_ID, HADM_ID, ICUSTAY_ID, CHARTTIME, ITEMID, VALUE, VALUEUOM, VARIABLE, MIMIC_LABEL]
Index: []</b>
</pre>

Would appreciate any help I can get.
