### ISSUE TITLE
Time-data issue

### ISSUE THREAD

**Issue by etsi123** [YerevaNN/mimic3-benchmarks#103]
If you run the command, 'python -m mimic3benchmark.scripts.create_decompensation data/root/ data/decompensation/'
you will have the error: ValueError: time data '2126-08-14' does not match format '%Y-%m-%d %H:%M:%S'. This makes sense since the time data is missing the hours/seconds/minutes component. However, if you go to the line of code causing the problem, and delete '%H:%M:%S' you get the error: ValueError: unconverted data remains:  18:59:00. I assume this means some of the data contains hours/minutes/seconds info and others don't. Has anyone encountered this problem? 
Thank you

**Comment by xiuwei1026** [comment]
@etsi123, Hi, have you solved the issue? I got the same error. Thanks.

**Comment by etsi123** [comment]
@xiuwei1026 Unfortunately no

**Comment by xiuwei1026** [comment]
@hrayrhar, sorry to bother, do you have an idea to fix the issue? Thanks.

**Comment by zoevas** [comment]
@[LINGLONGQIAN](https://github.com/LINGLONGQIAN)   Your solution it works, thank you very much for sharing it

**Comment by Bhumika-26** [comment]
@LINGLONGQIAN Thank you so much for your solution!!

**Comment by hrayrhar** [comment]
Sorry everyone for being idle on this issue. It is now fixed in the current version. This was the fix:

``` python
lived_time = (pd.to_datetime(deathtime) - pd.to_datetime(intime)).total_seconds() / 3600.0
```

**Comment by yudeng2022** [comment]
I got the same issue ... I used        git clone https://github.com/YerevaNN/mimic3-benchmarks/ to pull the script. Does that give me the most current version of the code?

Actually, slightly different, I experienced this when running the python -m mimic3benchmark.scripts.extract_subjects ../mimic_data data/root/ command. 
My error message is as the following 

` File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "1895-05-17 00:00:00" doesn't match format "%m/%d/%Y %H:%M", at position 5. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
cdsw@i4va2c7in9e3nn2a:~/working_folder/Yu/mimic3-benchmarks$ python -m mimic3benchmark.scripts.extract_subjects ../mimic_data data/root/`
