### ISSUE TITLE
freezing when run linear regression on length of stay

### ISSUE THREAD

**Issue by xiuwei1026** [YerevaNN/mimic3-benchmarks#110]
Has anybody had the same issue? When I run linear regression on length of stay, it freezes at "Reading data and extracting features...". Not sure it's my python environment issue or not. 
`    python -um mimic3models.length_of_stay.logistic.main --output_dir mimic3models/length_of_stay/logistic
`
![image](https://user-images.githubusercontent.com/76968919/106621356-7d558100-6540-11eb-8904-a8deb6ca42c7.png)

**Comment by alanflanders** [comment]
It finishes for me

**Comment by hrayrhar** [comment]
It just takes too long (a few hours or more), it does not freeze.
