### ISSUE TITLE
About min(+P, Se) metric.

### ISSUE THREAD

**Issue by qkrdmsghk** [YerevaNN/mimic3-benchmarks#111]
hello, may I know the meaning of metric "min(+P, Se)"?
And can I use it to compare with benchmarking methods?
Thank you very much!

**Comment by Hrant-Khachatrian** [comment]
It is a custom metric defined in [PhysioNet/Computing in Cardiology Challenge 2012](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3965265/). It was used in the [very early version](https://arxiv.org/pdf/1703.07771v1.pdf) of our paper, but we abandoned it later.

**Comment by qkrdmsghk** [comment]
> It is a custom metric defined in [PhysioNet/Computing in Cardiology Challenge 2012](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3965265/). It was used in the [very early version](https://arxiv.org/pdf/1703.07771v1.pdf) of our paper, but we abandoned it later.

Thank you very much for your clarification.
