### ISSUE TITLE
ValueError: Could not interpret optimizer identifier: 0.9

### ISSUE THREAD

**Issue by joaofonseca9** [YerevaNN/mimic3-benchmarks#120]
Error is at line 97 of in-hospital-mortality.main.py, where model.compile called.

I've tried some troubleshooting related to using tf.python.keras and pure keras but can't seem to find the problem

**Comment by Artchyy** [comment]
Hey, 


did you solve the problem? If yes, how? Get the same error

**Comment by wang67-jianli** [comment]
Hey,

did you solve the problem? If yes, how? Get the same error
