### ISSUE TITLE
Question about metric alignment

### ISSUE THREAD

**Issue by yzhHoward** [YerevaNN/mimic3-benchmarks#141]
Thanks for your great work! I find that there are different metrics (valueom) for one lab test, such as there are F and C for temperature, oz/kg/lbs for weight. Do you align them while preprocessing these data?

**Comment by hrayrhar** [comment]
Yes, we do standardize such features. For example, here is the [code](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3benchmark/preprocessing.py#L234) for weight.
