### ISSUE TITLE
 mimic3benchmark/mimic3csv.py repeated/copied lines

### ISSUE THREAD

**Issue by Saqibm128** [YerevaNN/mimic3-benchmarks#20]
Lines 189 and afterwards are repeated; moreover, they appear to have been repeated from inside a for loop but then indented to be outside the for loop. As a result, it appears that this portion of the code may not work.

Shouldn't line 184 and 185 be placed AFTER line 186 and line 187?

In fact, I get errors when code runs into this section of the code about rowno being used before its assignment.

**Comment by Saqibm128** [comment]
I am mostly raising this issue as I am trying to read the code and understand what potential issues would have caused this design. Perhaps subject_id is not always set for some reason??

**Comment by Harhro94** [comment]
Hi @Saqibm128,

Please notice I merged a pull request which adds python3 support and `mimic3csv.py` is changed a little bit. 
We should remove the lines 195-201. I am not sure abut lines 193-194 and whether lines 188-189 should be before lines 190-191.

@turambar I think you can answer to these questions.

**Comment by Saqibm128** [comment]
I am not entirely sure what the purpose was or if the code is necessarily clear enough to understand on the first pass through. If the lines are necessary, then we should probably add some comments explaining it.

**Comment by turambar** [comment]
I reviewed the code -- those lines are to protect against an [off-by-one error](https://en.wikipedia.org/wiki/Off-by-one_error). To reduce I/O churn, we don't write one event row for every event row we read. Rather, we accumulate event rows by SUBJECT_ID until we encounter a row with a different SUBJECT_ID. At that point, we write out all of the accumulated rows for the previous SUBJECT_ID and begin accumulating rows for the new SUBJECT_ID. Thus, when we exit the loop, we have one SUBJECT_ID worth of rows to write out.

**Comment by turambar** [comment]
This issue has been superseded by https://github.com/YerevaNN/mimic3-benchmarks/issues/35
