### ISSUE TITLE
remove_outliers_for_variable

### ISSUE THREAD

**Issue by Saqibm128** [YerevaNN/mimic3-benchmarks#25]
I cannot find an instance where remove_outliers_for_variable is actually used in the current code base. This is problematic as there is an excellent dataset with valid ranges for variables that is not integrated into the codebase.

Is this actually the case or did I miss something? I used a full search on my cloned repo for the exact phrasing of the function name but I cannot seem to find it; I also see that read variable_ranges is used as an import but is never called.

**Comment by turambar** [comment]
@Saqibm128 yeah, you're right, it's not being used, as far as I can tell. I'm looking into it right now.

**Comment by turambar** [comment]
@Hrant-Khachatrian / @Harhro94: I just reran the pipeline -- it looks like we're not removing outliers or doing any rescaling! We need to make that explicit in our paper.

**Comment by turambar** [comment]
This has been superseded by https://github.com/YerevaNN/mimic3-benchmarks/issues/36
