### ISSUE TITLE
item_id_to_variable_map, variable_ranges.csv inconsistencies

### ISSUE THREAD

**Issue by Saqibm128** [YerevaNN/mimic3-benchmarks#28]
Currently, names for variables are inconsistent between the two. For example, item_id_to_variable_map.csv has a variable called "Heart Rate" while variable_ranges.csv has a variable called "Heart rate". This may not seem like much, but it is enough for clean functions and range checking functions to fail to recognize the same variable; a new column called Heart rate is created and populated solely with the impute value (i.e. the assumed normal heart rate of 86 bpm).

Because of #25, the issue is not too important in the current implementation, but it should be considered if remove_outliers_for_variables is ever run on the data.

**Comment by turambar** [comment]
I have a fix for this in https://github.com/YerevaNN/mimic3-benchmarks/pull/32. Take a look and provide feedback, if you will!

**Comment by turambar** [comment]
Merged https://github.com/YerevaNN/mimic3-benchmarks/pull/32
