### ISSUE TITLE
No dataset created

### ISSUE THREAD

**Issue by zzzace2000** [YerevaNN/mimic3-benchmarks#29]
I find all the scripts are successfully executed but when I create the dataset, there is no dataset in any of the folder.
Specifically, I run
```
python scripts/create_in_hospital_mortality.py data/root/ data/in-hospital-mortality/
```
And the script would output 0 record, and all the list file are empty.

Can anyone know what might go wrong?

I find plenty of files and records under data/root/, so I assume it is the last step which goes wrong.

**Comment by turambar** [comment]
@Harhro94 any thoughts on this? I'm going to rerun everything from scratch shortly so I'll get back to you @zzzace2000

**Comment by zzzace2000** [comment]
Hi, I manage to fix it by creating episodes for each train/ and test/ folder. So now it's working fine! Thanks!

**Comment by turambar** [comment]
@zzzace2000 Great!
