### ISSUE TITLE
KeyError while running python script

### ISSUE THREAD

**Issue by lordim** [YerevaNN/mimic3-benchmarks#39]
Hello,

I'm also trying to run the logistic regression python script on the in-hospital-mortality benchmark data. However, it is giving me a key error on capillary refill rate? Does it have something to do with the data?

(ICU_env) oggi2@oggi2-Precision-Tower-7910:/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/in_hospital_mortality/logistic$ python2 -u main.py --l2 --C 0.001
Namespace(C=0.001, epochs=100, features='all', l2=True, period='all')
==> reading data and extracting features
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    (train_X, train_y) = read_and_extract_features(train_reader)
  File "main.py", line 42, in read_and_extract_features
    X = common_utils.extract_features_from_rawdata(chunk, header, args.period, args.features)
  File "/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/common_utils.py", line 25, in extract_features_from_rawdata
    data = [convert_to_dict(X, header, channel_info) for X in chunk]
  File "/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/common_utils.py", line 16, in convert_to_dict
    if (len(channel_info[channel]['possible_values']) != 0):
KeyError: 'capillary refill rate'

Thank you!

**Comment by Harhro94** [comment]
Hi @lordim ,

Fixing #28 caused this. We lowercased all columns, but channel_info.json still contains the old names. 
I will lowercase the keys in channel_info.json file. This should help.

Hrayr

**Comment by lordim** [comment]
Hello,

I think the keyerror issue is fixed. But, it still gives me this error. What do you think could be the issue?

(ICU_env) oggi2@oggi2-Precision-Tower-7910:/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/in_hospital_mortality/logistic$ python2 -u main.py --l2 --C 0.001
Namespace(C=0.001, epochs=100, features='all', l2=True, period='all')
==> reading data and extracting features
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    (train_X, train_y) = read_and_extract_features(train_reader)
  File "main.py", line 42, in read_and_extract_features
    X = common_utils.extract_features_from_rawdata(chunk, header, args.period, args.features)
  File "/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/common_utils.py", line 25, in extract_features_from_rawdata
    data = [convert_to_dict(X, header, channel_info) for X in chunk]
  File "/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/common_utils.py", line 18, in convert_to_dict
    ret[i-1] = map(lambda x: (float(x[0]), float(x[1])), ret[i-1])
  File "/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/common_utils.py", line 18, in <lambda>
    ret[i-1] = map(lambda x: (float(x[0]), float(x[1])), ret[i-1])
ValueError: could not convert string to float: NEG


Thanks!

**Comment by Harhro94** [comment]
Today I noticed that some of our recent commits introduce changes in crated datasets. I opened one issue addressing a part of it. I am going to open another one addressing another part of this changes. 
Your issue is related to that. Please use this commit 4459f04a3b0202d4feefaf17e058ae4a69f8cc12 (Rerun with the same batch size, Dec 31, 2017) to re-create the data. Meanwhile we will work to remove these differences.

Here are the steps to re-create the data.
* delete current data
* `git clone 4459f04a3b0202d4feefaf17e058ae4a69f8cc12`
* create the data again

With this commit everything should be fine.

**Comment by Harhro94** [comment]
Hello @lordim,

This issue is completely solved now. You can use the latest version of code. I have checked that everything runs smoothly.
