### ISSUE TITLE
episode1 is missing for some subject_ids

### ISSUE THREAD

**Issue by Hrant-Khachatrian** [YerevaNN/mimic3-benchmarks#4]
Some `subject_id`s have episode2 but not episode1. Is this fine?

**Comment by Hrant-Khachatrian** [comment]
Episode1 for some patients was filtered out at some step. We just work with Episode 2+ in those cases

**Comment by alistairewj** [comment]
Just FYI there is a known issue in v1.4 where we have admission/discharge/transfer information for patients (and so they have an `icustay_id`) but we do not every observe any data for that stay (and so chartevents has no data for that `icustay_id`). So this is expected and using episode 2+ makes sense :+1:
