### ISSUE TITLE
Issues with running logistic regression python script

### ISSUE THREAD

**Issue by lordim** [YerevaNN/mimic3-benchmarks#43]
Hello,

I used the latest code to re-process the benchmarks. But I'm still getting an error. This is the error that I get when I tried to run logistic regression for decompensation and length-of-stay:

(ICU_env) oggi2@oggi2-Precision-Tower-7910:/media/oggi2/DATA2/kgp_new/mimic3-benchmarks/mimic3models/length_of_stay/logistic$ python2 -u main_cf.py 
Namespace(features='all', period='all')
==> reading data and extracting features
Traceback (most recent call last):
  File "main_cf.py", line 70, in <module>
    (train_X, train_y, train_actual) = read_and_extract_features(train_reader, chunk_size)
  File "main_cf.py", line 54, in read_and_extract_features
    ret = common_utils.read_chunk(reader, read_chunk_size)
  File "/media/oggi2/DATA2/kgp_new/mimic3-benchmarks/mimic3models/common_utils.py", line 31, in read_chunk
    ret = reader.read_next()
  File "/media/oggi2/DATA2/kgp_new/mimic3-benchmarks/mimic3benchmark/readers.py", line 35, in read_next
    return self.read_example(to_read_index)
  File "/media/oggi2/DATA2/kgp_new/mimic3-benchmarks/mimic3benchmark/readers.py", line 196, in read_example
    raise ValueError("Index must be from 0 (inclusive) to number of lines (exclusive).")
ValueError: Index must be from 0 (inclusive) to number of lines (exclusive).

And this is the error that I get for logistic regression of in hospital mortality and phenotyping:

(ICU_env) oggi2@oggi2-Precision-Tower-7910:/media/oggi2/DATA2/kgp_new/mimic3-benchmarks/mimic3models/phenotyping/logistic$ python2 -u main.py 
Namespace(features='all', period='all')
==> reading data and extracting features
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    (train_X, train_y) = read_and_extract_features(train_reader)
  File "main.py", line 36, in read_and_extract_features
    ret = common_utils.read_chunk(reader, reader.get_number_of_examples())
  File "/media/oggi2/DATA2/kgp_new/mimic3-benchmarks/mimic3models/common_utils.py", line 36, in read_chunk
    data["header"] = data["header"][0]
KeyError: 'header'

Thanks!

**Comment by Harhro94** [comment]
I run the same command locally (only for in-hospital mortality). I didn't get any error. 
I cannot guess why this happened. The only thing I can see is that all the errors are related to readers.
Please make sure we use the same versions of code.

**Comment by lordim** [comment]
I'm not sure if this will necessarily matter, but just to make sure, what versions of keras and sklearn are you using? I have all of your github code up to date so I'm just wondering if I have to use the same versions for backend. Thanks!

**Comment by Harhro94** [comment]
Keras - 2.0.8
Theano - 0.10.0b3+118.gaeb6e3c
scikit-learn - 0.19.1
pandas - 0.20.3

**Comment by lordim** [comment]
Hello,

the logistic regression models run now, but the lstm models are not working. For example, in in-hospital mortality, it is producing this error:

(ICUenv) oggi2@oggi2-Precision-Tower-7910:/media/oggi2/DATA2/icu_final/mimic3-benchmarks/mimic3models/in_hospital_mortality$ python2 -u main.py --network lstm -
-dim 256 --timestep 2.0 --mode train --batch_size 8
Using TensorFlow backend.
Namespace(batch_norm=False, batch_size=8, beta_1=0.9, depth=1, dim=256, dropout=0.0, epochs=100, imputation='previous', l1=0, l2=0, load_state='', lr=0.001, mode='train', network='lstm', optimizer='adam', prefix='', rec_dropout=0.0, save_every=1, size_coef=4.0, small_part=False, target_repl_coef=0.0, timestep=2.0, verbose=2)
==> using model lstm
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    model_module = imp.load_source(os.path.basename(args.network), args.network)
IOError: [Errno 2] No such file or directory

What could be the issue?

**Comment by Harhro94** [comment]
This one is easy to fix - just change `--network lstm` to `--network ../common_keras_models/lstm.py`. 
That old syntax was for Lasagne-based models, which I have removed from the repo, as Keras-based models perform better on all tasks.

I will update the README  to mention about this.

**Comment by lordim** [comment]
Thank you! That fixed it. Just a minor add, the log_every parameter is an unrecognized argument when I run the script.

**Comment by Harhro94** [comment]
Nice!
log_every is also related to Lasagne codes. It is the readme file that is
not updated.

Hrayr
