### ISSUE TITLE
Is there a pre-trained model? 

### ISSUE THREAD

**Issue by datduong** [YerevaNN/mimic3-benchmarks#46]
Hi, 

Is there a pre-trained model? I'm interested in using the hidden states for some other neural network models. 

Thanks.

**Comment by Harhro94** [comment]
Hi @datduong,

We plan to publish pre-trained models for each task and baseline soon. Before that, I can send you some pre-trained models.

**Comment by fvncc** [comment]
Hi, any updates on the pre-trained models? :)

**Comment by ashrafabdul** [comment]
Thank you for the excellent repository. I was wondering if we you would be willing to release the pre-trained models anytime soon?

**Comment by ashrafabdul** [comment]
Thank you @Harhro94 . Much appreciated!

**Comment by ShaAfr** [comment]
@hrayrhar, how can I use the pre-trained model that you have provided?
