### ISSUE TITLE
Can't find zero.normalizer pickle file

### ISSUE THREAD

**Issue by shiningliang** [YerevaNN/mimic3-benchmarks#57]
Hi Nice work first!
When I have prepared train and test set for in-hospital-mortality. I get an error like this
`File "E:/PythonProject/mimic3-benchmarks/mimic3models/in_hospital_mortality/main.py", line 58, in <module>
    normalizer.load_params(normalizer_state)`
`File "E:\PythonProject\mimic3-benchmarks\mimic3models\preprocessing.py", line 215, in load_params
    with open(load_file_path, "rb") as load_file:`
`OSError: [Errno 22] Invalid argument: 'E:/PythonProject/mimic3-benchmarks/mimic3models/in_hospital_mortality\\ihm_ts1.0.input_str:previous.start_time:zero.normalizer'`

I follow the instructions in the _**Building a benchmark**_ but I didn't got the zero.normalizer file.
Can anyone help me?

**Comment by Harhro94** [comment]
I haven't uploaded normalizer state files for all configuration. To create a state file with a specific configuration use script [`create_normalizer_state.py`](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3models/create_normalizer_state.py).

**Comment by shiningliang** [comment]
@Harhro94 Thanks for your reply. I'll try it.

**Comment by EmmaRocheteau** [comment]
Hi. Related to this. I want to recreate the results of the paper. Should I give the following arguments to the create_normalizer_state script?:
impute_strategy='previous', 
n_samples=-1, 
output_dir='.', 
start_time=Zero, 
store_masks=True, 
task='ihm', 
timestep=1.0
if I want to recreate the in-hospital-mortality baseline results?

**Comment by Harhro94** [comment]
Yes.

**Comment by safynaz** [comment]
please can you tell me, how you run this script, I wrote the following:
  >>python -um mimic3models.create_normalizer_state script --impute_strategy previous --n_samples -1 --output_dir . --start_time zero --store_masks True --task ihm --timestep 1.0 --data {Data path}
I don't know what i should write beside argument data but i put path of data and after i run this script, give me the following error:  
create_normalizer_state.py: error: unrecognized arguments: True

**Comment by safynaz** [comment]
please can you tell me, how you run this script, I wrote the following
    python -um mimic3models.create_normalizer_state script --impute_strategy previous --n_samples -1 --output_dir . --start_time zero --store_masks True --task ihm --timestep 1.0 --data {Data path}
I don't know what i should write beside argument data
Also, after i run this script, give me the following error:  
create_normalizer_state.py: error: unrecognized arguments: True

**Comment by Harhro94** [comment]
Hi @safynaz,

1. The boolean option `--store_masks True` should be used without the value part (i.e. just `--store_masks`). If you want to set it to false, you need to add the `--no-masks` option.

2. The `--data` argument should point to the directory where the ihm task is stored. It will be something like `data/ihm`.

**Comment by safynaz** [comment]
i edited the script to the following: 
(mimic3) D:\mimic3-benchmarks>**python -um mimic3models.create_normalizer_state --
impute_strategy previous --n_samples -1 --output_dir . --start_time zero --store
_masks --task ihm --timestep 1.0 --data D:\mimic3-benchmarks\data\in-hospital-mo
rtality**

But i found the following:
Namespace(data='D:\\mimic3-benchmarks\\data\\in-hospital-mortality', impute_strategy='previous', n_samples=-1, output_dir='.', start_time='zero', store_masks=True, task='ihm', timestep=1.0)
Processed 0 / 46 samples
Saving the state in .\ihm_ts:1.00_impute:previous_start:zero_masks:True_n:46.normalizer ...
Traceback (most recent call last):
  File "C:\Users\safy\Anaconda3\envs\mimic3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\safy\Anaconda3\envs\mimic3\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
  File "D:\mimic3-benchmarks\mimic3models\create_normalizer_state.py", line 90, in <module> main()
  File "D:\mimic3-benchmarks\mimic3models\create_normalizer_state.py", line 86,in main 
   normalizer._save_params(file_name)
  File "D:\mimic3-benchmarks\mimic3models\preprocessing.py", line 204, in _save_params with open(save_file_path, "wb") as save_file:
**OSError: [Errno 22] Invalid argument: '.\\ihm_ts:1.00_impute:previous_start:zero
_masks:True_n:46.normalizer'**

**Comment by farbodab** [comment]
@safynaz I assume you figured it out. But for those running into the same issue, it's being caused by windows not liking the ':' character in file names.

Solution: 

Line 55 of 'main.py' in mimic3models\in_hospital_mortality

Change to: normalizer_state = 'ihm_ts{}.input_str_{}.start_time_zero.normalizer'.format(args.timestep, args.imputation)

Should fix it :)

**Comment by Mengjielf** [comment]
@farbodab Thanks! It's very useful, i've solved it.
