### ISSUE TITLE
speeding up training times

### ISSUE THREAD

**Issue by pruales** [YerevaNN/mimic3-benchmarks#61]
I'm training the models on an Azure VM with 64 cores available but training only uses 1 from what I can tell, is there an option to make the training multi-core?

**Comment by Hrant-Khachatrian** [comment]
Dear @pruales, 

Thanks for your interest. Are you talking about CPU cores? We have trained the models only on GPUs (single GPUs actually). But as far as I remember the underlying frameworks should use the CPU cores automatically. Which Keras backend are you using?

**Comment by pruales** [comment]
Yes, I was using CPUs. I can try switching to GPUs though, but on CPU it was only using 1 core for some reason. I'm using tensorflow as my backend.
