### ISSUE TITLE
Range

### ISSUE THREAD

**Issue by OluOrojo** [YerevaNN/mimic3-benchmarks#63]
My research involves exploring computational architectures in particular neural networks to find, express and extract information to improve clinical decision making and patient outcomes by analysing ICU variables.

I am currently working on a subset of the medical data (MIMIC III) and would like to know if you have the average normal ranges for the variables used in the database. For clarity, the ranges I am referring to are the normal ranges (that is for patients not in ICU), for example, the normal range for temperature is 97°F (36.1°C) to 99°F (37.2°C). 

I am unable to obtain reliable ranges for all the variables from one source and I am hoping to obtain the ranges directly from your team as you are the source of the data and this reduces any discrepancies.

**Comment by Hrant-Khachatrian** [comment]
Dear @OluOrojo,

We only have [this list of ranges of variables](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3benchmark/resources/variable_ranges.csv), but I guess the purpose of this list is to detect clear mistakes in the dataset, so the ranges here are much wider than the "normal ranges" you are referring to.

**Comment by OluOrojo** [comment]
@Hrant-K

**Comment by Hrant-Khachatrian** [comment]
Sorry, we don't have the normal ranges. This list was manually compiled by our co-author David Kale.

**Comment by OluOrojo** [comment]
@Harhro94 hi what does valid range and outlier range mean from dataset? Is outlier range impossible?

**Comment by xydo1990** [comment]
@OluOrojo the column "OUTLIER LOW" mostly represents limits for impossible values like a negative weight does not make sense. The "OUTLIER HIGH" column seems to contain values which are very unlikely values due to little google research, but I do not have a medical background.

@Hrant-Khachatrian is there a reason for not using the outlier removal code? Did it decrease prediction outcome? Thanks a lot!

**Comment by thbuerg** [comment]
Adding to @xydo1990's question:
Is the value denoted unter 'IMPUTE' empiric from the data or derived by clinical  knowledge?
Thanks a lot!

**Comment by Harhro94** [comment]
First of all the file we are discussing wasn't used in our pipeline. @xydo1990, I recall that we found out that we don't use the outlier removal code very late, so decided to publish the first version of the benchmark datasets without outlier removal. 
The values listed in that file don't reflect the statistics of MIMIC-III datasets. @thbuerg, the values were derived based on clinical knowledge. @OluOrojo, something outside the outlier range is possible, but we would consider that as a mistake.
