### ISSUE TITLE
Class weights

### ISSUE THREAD

**Issue by EmmaRocheteau** [YerevaNN/mimic3-benchmarks#66]
I ran your main script in test mode with the best parameters for the standard LSTM. I noticed that the metrics for the two classes were very different. Did you not apply class weights? If not, why not?

**Comment by hrayrhar** [comment]
Hi @EmmaRocheteau,

Sorry for responding this late. If you still have this question please specify which tasks is the question about. Generally, we didn't use any tasks weights to keep the evaluation simple. Instead, we used evaluation metrics that are "robust" to label imbalance (e.g., AUC-ROC and AUC-PRC for binary classification or Kohen's kappa score for length-of-stay prediction). 

Hrayr
