### ISSUE TITLE
itemid_to_variable_map.csv status 

### ISSUE THREAD

**Issue by TVect** [YerevaNN/mimic3-benchmarks#67]
I note that we filter out the variable whose `STATUS == 'ready'` in `itemid_to_variable_map.csv` when we run `extract_episodes_from_subjects.py`

```
var_map = var_map.ix[(var_map.STATUS == 'ready')]
```

I don't know what  the STATUS column in `itemid_to_variable_map.csv`  means. 

And I wonder whether  i can use some more variables such as `Alanine aminotransferase` whose status is `verify` in `itemid_to_variable_map.csv`.

Thx.

**Comment by Harhro94** [comment]
Hi @TVect , 

The `STATUS` field in the `itemid_to_variable_map.csv` indicates whether preprocessing & cleaning functions are written for that variable. For variables that have `STATUS = ready`, the `mimic3benchmark/preprocessing.py` file contains preprocessing functions. 

If you want to add a new variable, you can try to write a code that preprocesses that variable  (similar to for example `clean_dbp` function of `mimic3benchmark/preprocessing.py`); add it into [`clean_fns`](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3benchmark/preprocessing.py#L266); and mark the status as READY.

**Comment by TVect** [comment]
@Harhro94 
OK. Thx.
