### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by wahma** [YerevaNN/mimic3-benchmarks#69]
Thank you for the code it made it a lot easier for me to use MIMIC data, couple of suggestions :
- Maybe add a verbosity parameter because it sure takes more time with all the printing
- And a good addition would be to have a progress bar for each task (I think that tqdm does this quite easily)

**Comment by hrayrhar** [comment]
Thanks @wahma , I just reduced the amount of printing and added tqdm to track progresses. You can view the changes [here](https://github.com/YerevaNN/mimic3-benchmarks/commit/da6fb45ee7a00f5051ec47bf15247045774c3604).

Hrayr
