### ISSUE TITLE
Import of mimic3benchmark module fails

### ISSUE THREAD

**Issue by alistairewj** [YerevaNN/mimic3-benchmarks#7]
Trying to run through the readme on Ubuntu:

```sh
~/git/mimic3-benchmarks$ python scripts/extract_subjects.py /data/mimic3/csv/ /data/mimic3/csv/
Traceback (most recent call last):
  File "scripts/extract_subjects.py", line 5, in <module>
    from mimic3benchmark.mimic3csv import *
ImportError: No module named mimic3benchmark.mimic3csv
```

It works if I move extract_subjects.py to the main folder - probably need to change to relative imports

**Comment by turambar** [comment]
@alistairewj! Thanks for stopping by! I was going to email you once we did our official "release" (probably sometime within the next week), but you found us. We'd really love to get your feedback on this. We have a paper attached to it under review for SIGKDD and awaiting upload to arXiv (also within the next week). I'll DM you for details.

Good catch. We probably also we need to turn this into a proper python package that can be installed with setup.py.

@Hrant-Khachatrian @Harhro94

**Comment by turambar** [comment]
@alistairewj Check out preamble I added to README for background.

**Comment by alistairewj** [comment]
It's great, really happy to see this. Will definitely be taking a deeper look at the code in due course. Question, for the filtering, which file is `stays.csv`? Or rather, what is it sourced from? Is it similar/based on `icustays.csv`?

**Comment by Hrant-Khachatrian** [comment]
for now we'll use PYTHONPATH to avoid such problems. The new readme reflects that.

`stays.csv` contains one line per ICU stay for the given subject. Usually it's just one line.
