### ISSUE TITLE
Normalizer

### ISSUE THREAD

**Issue by sz891016** [YerevaNN/mimic3-benchmarks#73]
Hello, I want reproduce your work in my computer. In create_normalizer_state.py , I found you just normalized data in /train folder, how about the test data, did it need to be normalized?

Look forword to your reply!

**Comment by Harhro94** [comment]
Hi @sz891016 ,

the `create_normalizer_state.py` file just computes means and standard variations on the train data and uses those statistics to normalize both the train and test data. Note, that it doesn't alter the files stored in data directories.
