### ISSUE TITLE
LSTM In-hospital mortality prediction

### ISSUE THREAD

**Issue by safynaz** [YerevaNN/mimic3-benchmarks#75]
Please tell me when run this script for mortality prediction:
**python -um mimic3models.in_hospital_mortality.main --network mimic3models/keras_models/lstm.py --dim 16 --timestep 1.0 --depth 2 --dropout 0.3 --mode train --batch_size 8 --output_dir mimic3models/in_hospital_mortality**

**_Give me the following error:_**
Using TensorFlow backend.
Namespace(batch_norm=False, batch_size=8, beta_1=0.9, data='D:\\mimic3-benchmarks\\mimic3models\\in_hospital_mortality\\../../data/in-hospital-mortality/', depth=2, dim=16, dropout=0.3, epochs=100, imputation='previous', l1=0, l2=0, load_state='', lr=0.001, mode='train', network='mimic3models/keras_models/lstm.py', normalizer_state=None, optimizer='adam', output_dir='mimic3models/in_hospital_mortality', prefix='', rec_dropout=0.0, save_every=1, size_coef=4.0, small_part=False, target_repl_coef=0.0, timestep=1.0, verbose=2) Traceback (most recent call last):
  File "C:\Users\safy\Anaconda3\envs\mimic3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\safy\Anaconda3\envs\mimic3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\mimic3-benchmarks\mimic3models\in_hospital_mortality\main.py", line 57, in <module>
    normalizer.load_params(normalizer_state)
  File "D:\mimic3-benchmarks\mimic3models\preprocessing.py", line 215, in load_params
  with open(load_file_path, "rb") as load_file:
**OSError: [Errno 22] Invalid argument: 'D:\\mimic3-benchmarks\\mimic3models\\in_h
ospital_mortality\\ihm_ts1.0.input_str:previous.start_time:zero.normalizer'**

Please help me to solve this issue, Thanks in advance

**Comment by oyjwhy** [comment]
You may lose the file "ihm_ts1.0.input_str:previous.start_time:zero.normalizer" in the directory "mimic3-benchmarks/mimic3models/in_hospital_mortality/" or the name of the file is inconsistent with the line 55 in "mimic3-benchmarks/mimic3models/in_hospital_mortality/main.py". Because the name contains ":" that can be replaced by another symbol in WIN OS.
