### ISSUE TITLE
LOS training time

### ISSUE THREAD

**Issue by niuguy** [YerevaNN/mimic3-benchmarks#77]
Hi, would you mind to disclose your training time on Los with LSTM? 

I'm using one Telsa V100-SXM2-16GB, 4G CPU, and 26G memory.  It spends me almost half an hour on one epoch. Is that unnormal or not?

Thanks

**Comment by EmmaRocheteau** [comment]
I'm training on an Azure virtual machine with multiple GPUs and it's taking around 250s per chunk, so that's slightly over 4 minutes, so I would imagine that it's pretty normal for your machine?

**Comment by niuguy** [comment]
> I'm training on an Azure virtual machine with multiple GPUs and it's taking around 250s per chunk, so that's slightly over 4 minutes, so I would imagine that it's pretty normal for your machine?

Thanks a lot for the reply.
Got it. So it is LSTM itself that costs so much.
