### ISSUE TITLE
OverflowError: Overflow in int64 addition

### ISSUE THREAD

**Issue by congxingzhu** [YerevaNN/mimic3-benchmarks#79]

**Comment by shaoxiongji** [comment]
Did you solve this issue? I have encountered the same one.

**Comment by shaoxiongji** [comment]
`def add_age_to_icustays(stays):
    stays['INTIME'] = pd.to_datetime(stays['INTIME']).dt.date
    stays['DOB'] = pd.to_datetime(stays['DOB']).dt.date
    stays['AGE'] = stays.apply(lambda e: (e['DOB']-e['INTIME']).days/365, axis=1)
    stays.loc[stays.AGE < 0, 'AGE'] = 90
    return stays`

**Comment by congxingzhu** [comment]
Did you solve that issue? I remember I solved that by modifying something in the file, but I forgot. If you haven't solved it, I will try to recall it.

________________________________
