### ISSUE TITLE
No default for phenotype_definitions

### ISSUE THREAD

**Issue by alistairewj** [YerevaNN/mimic3-benchmarks#8]
`python extract_subjects.py /data/mimic3/csv/ /data/mimic3/csv/` fails:

```python
Traceback (most recent call last):
  File "extract_subjects.py", line 60, in <module>
    phenotypes = add_hcup_ccs_2015_groups(diagnoses, yaml.load(open(args.phenotype_definitions, 'r')))
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

I need to specify the phenotype for it to work: `python extract_subjects.py /data/mimic3/csv /data/mimic3/csv -p resources/hcup_ccs_2015_definitions.yaml` - I think it would be fair to use this resource file as the default, if there is no user input.

**Comment by turambar** [comment]
Good call. I'll make that change (or accept a PR)!

**Comment by Hrant-Khachatrian** [comment]
this is fixed
