### ISSUE TITLE
Question - Categorical Variables Handling 

### ISSUE THREAD

**Issue by SibghatUllah13** [YerevaNN/mimic3-benchmarks#82]
Hi,

I was unable to find the part of the Code that handles the Categorical Variables (i.e., converts them to one hot vector etc.) and feeds them to the LSTM based models. Would it be possible for to point me to the right python script/function that accomplishes it. 

Best,

**Comment by hrayrhar** [comment]
Hi,

As I remember the discretizer [class](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3models/preprocessing.py#L11) does that. It gets the needed information from [this](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3models/resources/discretizer_config.json) config file.
