### ISSUE TITLE
OverflowError: Overflow in int64 addition

### ISSUE THREAD

**Issue by ElAbedHoussem** [YerevaNN/mimic3-benchmarks#84]
Hello, 
I just start testing this work.
 Just by runing the first command : **python3 -m mimic3benchmark.scripts.extract_subjects ../houssem/data data/root** , I found this issue :  

>     raise OverflowError("Overflow in int64 addition")
>     OverflowError: Overflow in int64 addition

 which is caused by this instruction in **mimic3csv.py** : 

`stays['AGE'] = (stays.INTIME - stays.DOB).apply(lambda s: s / np.timedelta64(1, 's')) / 60./60/24/365`

can you please explain to me the cause of this error

**Comment by ElAbedHoussem** [comment]
this issue was caused by pandas version . by using pandas==0.20.3 this issue was fixed

**Comment by shaoxiongji** [comment]
For pandas==0.25.1, 
```
def add_age_to_icustays(stays):
    stays['INTIME'] = pd.to_datetime(stays['INTIME']).dt.date
    stays['DOB'] = pd.to_datetime(stays['DOB']).dt.date
    stays['AGE'] = stays.apply(lambda e: (e['DOB']-e['INTIME']).days/365, axis=1)
    stays.loc[stays.AGE < 0, 'AGE'] = 90
    return stays
```

**Comment by johntiger1** [comment]
Thank you, this helped me

**Comment by nftd** [comment]
I had the same situation. I am using windows, I had to install conda and install pandas 0.23.4 to run the scripts.

**Comment by raquelaoki** [comment]
Pandas version '1.1.2' also has the same error. The following suggested [here](https://stackoverflow.com/questions/56720783/how-to-fix-overflowerror-overflow-in-int64-addition) works: 

df['date_of_admission'] = pd.to_datetime(df['date_of_admission']).dt.date
df['DOB'] = pd.to_datetime(df['DOB']).dt.date
df['age'] = df.apply(lambda e: (e['date_of_admission'] - e['DOB']).days/365, axis=1)

**Comment by xiuwei1026** [comment]
Pandas '1.1.3' has the same error, and met other errors trying to downgrade Pandas with Python 3.8.5. Below modification of the code solves the issue.

> Pandas version '1.1.2' also has the same error. The following suggested [here](https://stackoverflow.com/questions/56720783/how-to-fix-overflowerror-overflow-in-int64-addition) works:
> 
> df['date_of_admission'] = pd.to_datetime(df['date_of_admission']).dt.date
> df['DOB'] = pd.to_datetime(df['DOB']).dt.date
> df['age'] = df.apply(lambda e: (e['date_of_admission'] - e['DOB']).days/365, axis=1)

**Comment by ztyreg** [comment]
> I had the same situation. I am using windows, I had to install conda and install pandas 0.23.4 to run the scripts.

Got an error when downgrading to 0.20.3 using python 3.7. But 0.23.4 worked.

**Comment by Victorfy** [comment]
stays['AGE'] = (stays.OUTTIME - stays.INTIME).dt.days / 365.25

**Comment by k3ybladewielder** [comment]
with pandas 1.3.4 had same issue

```OverflowError: Overflow in int64 addition```

**Comment by Michelingweo** [comment]
def add_age_to_icustays(stays):
    stays.INTIME = pd.to_datetime(stays.INTIME).dt.date
    stays.DOB = pd.to_datetime(stays.DOB).dt.date
    stays['AGE'] = stays.apply(lambda e:(e.INTIME - e.DOB).days/365, axis = 1)
    stays.loc[stays.AGE < 0, 'AGE'] = 90
    return stays
