### ISSUE TITLE
Help about Re: Multitask learning and benchmarking with clinical time series data

### ISSUE THREAD

**Issue by Gaozhy99** [YerevaNN/mimic3-benchmarks#86]
Hrant Khachatrian,

Hi, my name is Richard, and i working at Data & AI algorithm department of Ping-an Group which is biggest Insurance Company in China.
Recently, i read your article “Multitask learning and benchmark with clinical time series data”. First of all, i really like your work. Secondly, my team have some research at the same area as you do. We got lots of demand from insurance product department which has serious illness insurance services. They wants us to have a model that could check whether necessary and useful or not the ICU claim of our costumer (patient) settled.

We need your help and help is to get data-sets of your four benchmark tasks.

We use multitask LSTM models with a little bit progress and private data-set which is from Data department and can not disclose. We have a small AUC rise at 3 tasks, and then we wanna test at mimic3 public data-set. We download your scripts(mimic3-benchmarks-v1.0.0-alpha.zip) and run at python environment(python 3.6.1 and 3.7.5 with numpy 1.16.4 and pandas 0.24.2) with steps on paper(page 9 and 10). we got lots of error back. Even reprogram some scripts, we can not get same number of records of data-sets as your paper claimed.
We wanna cite your benchmark paper and publish our work, but we need your original data-sets of four benchmark tasks.

To be the simple way, you can send a link that we download your original data-sets of four benchmark tasks, or we need your help to update your scripts and we translate data-sets by our self.

My Email address is vincent_gao99@hotmail.com

Looking forward for your reply.
Best wishes

Richard Gao
2020.01.02

**Comment by hrayrhar** [comment]
Hi Richard,

If you still have this problem, please send some details about the errors you get. Unfortunately, we cannot give a link to download the final benchmark datasets, as it will violate the privacy constraints of the MIMIC-III dataset.

Hrayr
