### ISSUE TITLE
Please post Numpy, Pandas, and Tensorflow Versions 

### ISSUE THREAD

**Issue by amoldwin** [YerevaNN/mimic3-benchmarks#87]
I ran into several issues when running the preprocessing scripts that required changing ".ix" to ".loc" and similar fixes. It would be great if you could post the original library versions (pandas, numpy, tensorflow, etc) this was developed with so we can run the code in the matching environment. Thank you!

**Comment by hrayrhar** [comment]
I think it is pandas' version that might make difference. As I remember we were using pandas 0.23.4.

**Comment by hrayrhar** [comment]
I think we might have used even older versions. Versions listed in [requirements.txt](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/requirements.txt ) file should be the needed ones.

**Comment by atreyasha** [comment]
Was having trouble with the tensorflow versions, for me the IHM task worked with `tensorflow==1.15.2` or `tensorflow-gpu==1.15.2`

**Comment by amoldwin** [comment]
Thank you both! It seems to be working now with pandas 0.20.3 and tensorflow 1.15.0.
