### ISSUE TITLE
Evaluation Result of LR

### ISSUE THREAD

**Issue by RoonakR** [YerevaNN/mimic3-benchmarks#89]
Hi. I ran the commands for LR of hospital mortality suggested in your README (python -um mimic3models.in_hospital_mortality.logistic.main --l2 --C 0.001 --output_dir mimic3models/in_hospital_mortality/logistic)

but the result is :
AUC of ROC = 0.6700652803645508
AUC of PRC = 0.2237832554921843

which is quite different from your paper (AUC-ROC 0.848, AUC-PR 0.474). could you please explain to me where I'm wrong? thanks a lot.

**Comment by hrayrhar** [comment]
Hi @RoonakR,

No idea what is happening. I suggest to check the following two things:

1) That the generated data is correct. You can check this by running the test described [here](https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3benchmark/tests).

2) That you use the intended versions of libraries. See [here](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/requirements.txt).

Hrayr
