### ISSUE TITLE
Git clone error

### ISSUE THREAD

**Issue by johntiger1** [YerevaNN/mimic3-benchmarks#93]
Running a git clone of the repo today (April 15, 2020) and getting this error: 

![image](https://user-images.githubusercontent.com/14852840/79351354-92581980-7f06-11ea-8592-217d14609bbc.png)

Any idea on what's happening?

**Comment by hrayrhar** [comment]
Hi @johntiger1,

That's a strange error. Are you using a windows machine. I suspect it can be something related to file names.

**Comment by johntiger1** [comment]
Interesting, I tried the git clone again on Linux and it worked. But yes, windows is still broken as of right now:
![image](https://user-images.githubusercontent.com/14852840/79701249-974ffc80-8269-11ea-9eda-4f93c63def3e.png)

**Comment by BarryRun** [comment]
ph_ts1.0.input_str:previous.start_time:zero.normalizer

This is not a valid filename in Windows with a ‘:' in it. @hrayrhar @johntiger1
