### ISSUE TITLE
Possible issues in the preprocessing of Glasgow coma scale?

### ISSUE THREAD

**Issue by momih** [YerevaNN/mimic3-benchmarks#98]
There are some peculiarities I've noticed in the preprocessing of GCS scores:

- There are duplicate categories created for the same 'actual value' because there is a number in the text of the CHARTEVENTS value. Like  "2 To pain" & "To Pain" or "6 Obeys Commands" & "Obeys Commands". These are considered separate categories when they should be the same. The 3 GCS scores are one-hot encoded into a vector almost double the size because of this, maybe this redundancy could be removed?

- The GCS total score is not a sum of the 3 individual scores in some episodes because of imputation. For eg, if the entire GCS total score column has all missing values for a sample, the normal value (15) is imputed for all time steps. So say, some time steps have the lowest scores for the three individual scores, the total score is given as 15 for that timestep when it should be 3. 

I've only generated the data for the mortality task, btw.

**Comment by hrayrhar** [comment]
Hi @momih ,

All these peculiarities come from the data collection process. We chose to not standardize similar values like "2 to pain" and "to pain" in the data processing stage. However, the baselines we developed map those similar entries to the same category ([link](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3models/resources/channel_info.json)).

For the second issue we chose to do nothing, as there is not obvious data processing step that can be done.
